/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
#include <stdio.h>
/* Header for class com_example_moderato_cvcv_OpencvNativeClass */

using namespace std;
using namespace cv;

#ifndef _Included_com_example_moderato_cvcv_OpencvNativeClass
#define _Included_com_example_moderato_cvcv_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_moderato_cvcv_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
int toGray(Mat img, Mat& gray);

JNIEXPORT jint JNICALL Java_com_example_moderato_cvcv_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
